---
title: "My first story"
---

The beauty of data science is that it often provides audiences with information clearly and instantly based on numerical evidence. For instance, I created a 3D visualiation about how people migrantes in the world using data from the United Nations. It showed where migrants come from and where they go. Media often gives the audience the impression that most of the migrants come from the Middle East area and go to North America or Europe. However, the visualization illustrated that intra-migration, migration of people within an area, is more common. A surprising number of people moved within western Europe or eastern Europe.

As products of data science deliver convincing facts and messages, data scientists need to keep in mind how they can go wrong.

*Data Feminism* introduced several actual incidents about when it worked well and when it did not work perfectly or failed. Christine Darden and Gloria Champine from Langley’s Equal Opportunity Office proved the gender inequality at Langley and visualized it effectivly communicate that the institution did not promote women as much as men did even when they had identical academic credentials and job performance. As a result, the institution promoted Darden and took a step forward for equal opportunity. While data scientists take pride in creating a product that is convincing but not misleading simultaneously, we sometimes forget about the background story of the data. A smith alumnae, Betty Friedan did not consider how multiple dimensions of identity such as gender, race, class, etc would interact with each other when discussing feminism. Understanding all the behindstory of the data and how they relate to the message we want to deliver are difficult and burdensome, yet given the power of what data science can do, it is a needed task. *Data Feminism* taught me one of the important responsibities as a data scientists. 
