---
title: "The Process of Eliminating Discrimination"
---

I have always wondered if voicing the problems minority groups face, fighting against the oppressive system, and figuring out the way to improve the situation are the responsibilities of the minority people, because, as *Data Feminism* states, “those who occupy positions of privilege in society are able to remain innocent of the privilege.” While there are many exceptions, especially in Japan, feminism is often thought of as an idea that is important and beneficial mostly for women. Racism is thought to be non-existant in a mostly homegeneous society when historically numbers of different ethnic groups have been living in Japan for centuries. The power chapter in *Data Feminism* helped me organize my thoughts about the process of eliminating discrimination.

I tend to hold an optimistic view; for the gender, race, and other social issues, I believe that fixing the problems will give people, not only the minoritized ones, but also the majority people,  more freedom about the choices they make in their lifetime, regardless of their gender, race, or any other identity or background. However, the people who currently hold the power to change the situation mostly are male, white people with wealthy backgrounds. As the chapter mentioned, although those people at the top may not have malicious intentions, they may be oppressing the minoritized group unintentionally and not notice the fact. In order to prevent privilege hazards, diversity of the people in the organizations are cruicial. Despite the need, the number of students studying Computer Science who may be able to fix the current version of technology to respect more diversity in the future has been declining since 1984. We discussed in a group how we can give an impact to society without waiting for the number of female Computer Science students to increase decades later. 

The chapter also explained four domains of the matrix of domination and how Joy Buolamwini and other inspiring individuals have tackled the social issues via one or more of the domains. While even an idealistic person believes that there is a long way to go, by analyzing problems and breaking them down into domains, I felt that it seems much clearer what are some steps required for a change. The question I have now is whether the success rate will change depending on the order of dealing with the domain. 
