---
title: "Collect, Analyze, Imagine, Teach"
---

  The Detroit Board of Commerce introduced a Residential Security Map in 1939 to estimate the risk of lending loans based on the customers’ residential location. The data and the system were used to indirectly discriminate against the racial minority and resulted in oppressing the minoritized group to change the power structure or climb up the social ladder. The chapter explored how the current society categorizes individuals and determines an individual’s future based on historical records and other past information. 

  When I was reading this chapter, I was trying to think if there is any similar incident that happened around me. While I could not come up with a personal story, I thought about the discriminations against historically minoritized groups that still occur today in Japan. Japanese administration adopted a caste system starting in the 16th century, and it discriminated against entertainers and craftsmen and whose occupations were related to the death of creatures. While the government established laws prohibiting the caste system in the 19th century, the discriminations against the descendants of the group of people who live in the area the minoritized people were forced to live still exist. For example, I have heard that some parents still disapprove if their child wants to marry a person of the minoritized group. Another incident is some real estate companies still check whether the property used to be the area the minoritized group lived. However, the data regarding such discriminatory acts do not seem to exist or be available to the public. 

  The situation is identical to the problem mentioned in the chapter about the traffic accidents the Detroit Geographical Expedition and Institution faced. People in Japan barely know these incidents and recognize the discrimination as historical events that were resolved already. As the authors wrote “The ability to sidestep politics in itself is a privilege,” I believe people who live in Japan, including myself, need to recognize their privileges and “challenge the unjust status quo.” From understanding history, culture, and the context of the current social system, we can step forward to the co-liberation. 
